name: gotest
on:
    push:
    pull_request:
    
jobs:
    gotest:
        name: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
             
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.60